### PR TITLE
Update Dockerfile & add docker-compose.yml

### PR DESCRIPTION
**Pull request by dotWee**
The following changes have been made:

- Updated the Dockerfile based upon @Alexxanddr's initial work (https://github.com/sberk42/fritzbox_exporter/pull/4) 
- Added a custom listen-address env variable to the Dockerfile (https://github.com/sberk42/fritzbox_exporter/commit/9e1b95bad060e83c371c4a7e617739f400fc061d)
- Added a `docker-compose.yml` (https://github.com/sberk42/fritzbox_exporter/commit/15f05f7a1fe656b5bc974aa5c6b08baa0fb9d036)
- Added documentation & notes regarding the usage with docker/docker-compose to the README (https://github.com/sberk42/fritzbox_exporter/pull/5/commits/6986685424527ca1c60ea0371e7b61b3d429817b)

### CODE REVIEW

**Comment by stephanroslen** [comment]
Tried it - works perfectly

**Comment by BangerTech** [comment]
Hi and thanks for your Work. 
Everything works fine expect the CPU Data i get an Error:  Error loading data.lua for data.usbOverview.devices.*.partitions.0.usedStorageInBytes: Error calling login_sid.lua: Get "http://fritz.box/login_sid.lua": dial tcp: lookup fritz.box on 127.0.0.11:53: no such host
Running on a 7590 with 7.24 firmware. What could this error solve?
Thanks

**Comment by dotWee** [comment]
> Hi and thanks for your Work.
> Everything works fine expect the CPU Data i get an Error: Error loading data.lua for data.usbOverview.devices.*.partitions.0.usedStorageInBytes: Error calling login_sid.lua: Get "http://fritz.box/login_sid.lua": dial tcp: lookup fritz.box on 127.0.0.11:53: no such host
> Running on a 7590 with 7.24 firmware. What could this error solve?
> Thanks

Looks like the docker container can't resolve the host `fritz.box`.  

This can be easily solved by either adding `--dns YOUR_FRITZBOX_IP` to your `docker run` command or adding `dns: YOUR_FRITZBOX_IP` to your `docker-compose.yml` file.  

Full example for `docker run`: 

```bash
 $ docker run -e 'USERNAME=your_fritzbox_username' \
     --dns YOUR_FRITZBOX_IP \
     -e 'PASSWORD=your_fritzbox_password' \
     -e 'GATEWAY_URL="http://YOUR_FRITZBOX_IP:49000"' \
     -e 'LISTEN_ADDRESS="0.0.0.0:9042"' \
     fritzbox-prometheus-exporter:latest
 ```

Full example for `docker-compose`: 

```yaml
version: '3'
 services:
   fritzbox-prometheus-exporter:
     hostname: fritzbox-prometheus-exporter
     dns: YOUR_FRITZBOX_IP # 192.168.0.1
     build:
       context: .
       dockerfile: Dockerfile
     container_name: fritzbox-prometheus-exporter
     ports:
       - "9042:9042"
     #expose:
     #  - "9042"
     restart: unless-stopped
     environment:
       USERNAME: your_fritzbox_username 
       PASSWORD: your_fritzbox_password
       GATEWAY_URL: http://YOUR_FRITZBOX_IP:49000
       LISTEN_ADDRESS: 0.0.0.0:9042
 ```

I'll add this to the README documentation later since this could be a common issue, thanks!

**Comment by BangerTech** [comment]
thanks man i´ll try this out tonight!! 
great job!!

**Comment by BangerTech** [comment]
just tried it right away but now i get:
Error loading data.lua for data.ramusage.series.0.-1: To many failed logins, login blocked for 5 seconds
whats now ;-)

**Comment by stephanroslen** [comment]
> just tried it right away but now i get:
> 
> Error loading data.lua for data.ramusage.series.0.-1: To many failed logins, login blocked for 5 seconds
> 
> whats now ;-)
> 
> 

You need to configure your username and password of the FritzBox. (if it is in userless mode, you can use admin as username)

**Comment by BangerTech** [comment]
thanks @stephanroslen got it :-)

**Comment by Frepke** [comment]
Hi,

When I try to run the docker-compose.yml I've got the following error:
```
Building fritzbox-prometheus-exporter
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /opt/containers/fritzexporter/Dockerfile: no such file or directory
```

**Comment by dotWee** [comment]
Probably because the docker image is outdated. @Frepke try this docker-compose:

```yml
version: '3'
 services:
   fritzbox-prometheus-exporter:
     hostname: fritzbox-prometheus-exporter
     build: https://github.com/dotWee/docker-fritzbox-prometheus-exporter.git
     container_name: fritzbox-prometheus-exporter
     # for dns issues like "dial tcp: lookup fritz.box on 127.0.0.11:53: no such host"
     # uncomment and fill the following line:
     # dns: YOUR_FRITZBOX_IP
     ports:
       - "9042:9042"
     #expose:
     #  - "9042"
     restart: unless-stopped
     environment:
       USERNAME: your_fritzbox_username 
       PASSWORD: your_fritzbox_password
       GATEWAY_URL: http://192.168.0.1:49000
       LISTEN_ADDRESS: 0.0.0.0:9042
```

The `build: https://github.com/dotWee/docker-fritzbox-prometheus-exporter.git` statement will cause Docker to build the latest image for you.

**Comment by dotWee** [comment]
In case building the docker image on your host takes to much resources I'm going to create an automated GitHub action to build an publish a docker image.

**Comment by Frepke** [comment]
thanks, the previous compose file worked for me.
only have to figure out how to connect this container to prometheus :)

**Comment by dotWee** [comment]
Alright, just ask if you're getting stuck or need help!

**Comment by Frepke** [comment]
> Alright, just ask if you're getting stuck or need help!

I will do, but first I'll try to figure it out myself (it's better for learning 😉)

**Comment by Frepke** [comment]
Connecting with Prometheus is done, but the container won't run because of some errors:

```
Recreating fritzbox-prometheus-exporter ... done
Attaching to fritzbox-prometheus-exporter
fritzbox-prometheus-exporter    | metrics available at http://0.0.0.0:9042/metrics
fritzbox-prometheus-exporter    | services loaded
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | GetInfo: SAOPFault: UPnPError 401 (Invalid Action)
fritzbox-prometheus-exporter    | Error getting metric values for data.usbOverview.devices.*.partitions.0.totalStorageInBytes: hash 'data' has no element 'usbOverview'
fritzbox-prometheus-exporter    | Error getting metric values for data.usbOverview.devices.*.partitions.0.totalStorageInBytes: hash 'data' has no element 'usbOverview'
```

The 5530 hasn't a USB port.
How can I use the right metrics for the 5530?

kr.,
Frepke

**Comment by Frepke** [comment]
Still the question, how to use the right metrics for the 5530?

**Comment by DanielWeeber** [comment]
@sberk42 please merge

**Comment by sberk42** [comment]
merged - together with several others

**Pull request merged**
